name: default_state_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  currency_text_input_formatter: ^2.1.9
  flutter:
    sdk: flutter
  intl: ^0.18.0
  syncfusion_flutter_gauges: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
